### ISSUE TITLE
rna-transcription: two error handling tests return Char

### ISSUE THREAD

**Issue by rootulp** [exercism/elm#174]
Two [tests](https://github.com/exercism/elm/blob/master/exercises/rna-transcription/tests/Tests.elm#L27
) on the rna-transcription exercise return type `Err Char` but it's not immediately clear why these `Char`s are chosen. The user may infer that the `Err` should return the first `Char` in the DNA strand but this isn't pointed out in the README. 

The [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/rna-transcription/canonical-data.json) doesn't appear to have these two error handling tests. I propose removing them or replacing them with a `Err String` where the String is something like `Invalid input`

**Comment by petemcfarlane** [comment]
An alternative approach would be to update the README? Personally I didn't struggle to see that it returned the first invalid Char in the strand, I quite enjoyed the exercise as it is!

**Comment by petemcfarlane** [comment]
A benefit of using a `Result` type is that you can capture unique information in the `Err`, otherwise you could just use a `Maybe`. If you always return `Err "Invalid input"` for any error, you may as well return a `Maybe.Nothing`. If you want to show why there was a failure you might do `Result.Err "'X' is not a valid nucleotide"` or `Result.Err "'Y' is not a valid nucleotide"`

**Comment by rootulp** [comment]
I like your suggestion of `Result.Err "'X' is not a valid nucleotide"` where `X` is the first invalid nucleotide.
