### ISSUE TITLE
Hamming - return Result rather than Maybe

### ISSUE THREAD

**Issue by petemcfarlane** [exercism/elm#179]
Just a thought really, I thought it may be more interesting to use a `Result` return type, rather than a `Maybe` to handle the exception cases - it could be a good way to introduce people to the Result type too?

**Comment by petemcfarlane** [comment]
PS happy to write/submit a PR if anyone thinks it's a good idea

**Comment by rootulp** [comment]
The [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/hamming/canonical-data.json) indicate these should be Errors but [currently](https://github.com/exercism/elm/blob/master/exercises/hamming/tests/Tests.elm#L48) they're `Nothing` b/c of the `Maybe` type. I'm in favor of replacing with a `Result` type that can have a `String` error similar to the canonical data.

**Comment by petemcfarlane** [comment]
I've added a PR, but since opening this issue, I'm not sure there's a whole load of benefit in using a Result when the error message is always the same? Maybe that's just me learning about using `Result` types. What do other people think? Is a `Result` more useful when there's more than one way something can fail? Or does `Result` still imply more than a `Maybe` with it's name, as it's the result of a function/calculation? What would you likely use in a production app?

**Comment by neganp** [comment]
I would agree that a `Result` type is better for this exercise because there are several ways the function could fail, and we only *happen* to see one. There could, for instance, be an invalid nucleotide. It might be worth looking in to getting such an example into the problem spec.

**Comment by tuxagon** [comment]
@neganp, that's a fair point. In addition to changing the spec, it would also be better to not use a string and have a union type along the lines of `type Error = Invalid | DifferentLengths`. That would be more idiomatic elm because you can rely on types more heavily instead of just the `String` type. I say it is more idiomatic because then the caller could handle the different errors instead of matching on strings, which is very error prone.

**Comment by neganp** [comment]
That's a good thought! :+1:

**Comment by petemcfarlane** [comment]
Ok, so the only errors we have are DifferentLengths right now, do you think another error we could test for and add to the error union type would be `InvalidNucleotide 'X'` for example?

**Comment by tuxagon** [comment]
@petemcfarlane I think that makes sense; however, I didn't see anything in the README that details what "invalid" means. Adding it would feel more code complete, but what is considered invalid would probably need detailed out in the README. For this specific issue, it might be too much. Do you agree @neganp?

**Comment by neganp** [comment]
I think, based on this thread, the more complicated fix would look something like this:
 
- [ ] Change the test cases to expect union types instead of strings; the new return value would be something like
```elm
type alias ExpectedType = Result TranscriptionError Error
```
- [ ] Make sure the tests hit both kinds of error (this Elm has more cases than are included in the canonical problem description, which is fine).
- [ ] Warn learners in the README that inputs can contain invalid nucleotides and/or have mismatched lengths.
- [ ] (Maybe) Add the expected union type to the exercise template? Defining a type based on error messages or reading the test code might be confusing.
```elm
type TranscriptionError = MismatchedLengths | InvalidNucleotide Char
```

Have I missed anything?

**Comment by leojpod** [comment]
I think we need to define the Union type for the error else it's gonna be hard to write the test will it not?

**Comment by leojpod** [comment]
![image](https://user-images.githubusercontent.com/4479457/48073899-fe960000-e1df-11e8-9a06-3a59704767a6.png)
why did GH do that? I didn't unassigned anyone :x

**Comment by tuxagon** [comment]
@leojpod Can you clarify what you are referring to?

**Comment by leojpod** [comment]
@tuxagon 
I was referring to this: 
> [ ] (Maybe) Add the expected union type to the exercise template? Defining a type based on error messages or reading the test code might be confusing.

Will it not be hard to tests which error we get if we are not expecting a specific union type for the error?

**Comment by tuxagon** [comment]
I guess that's where I'm confused. From my perspective, @neganp is suggesting a union type for the possible errors with 
```elm
type TranscriptionError = MismatchedLengths | InvalidNucleotide Char
```
From your comment
> I think we need to define the Union type for the error else it's gonna be hard to write the test will it not?

I see you and @neganp's suggestion aligning.

That checkbox, as I understand it, is proposing we also add the error for a student to use in the exercise stub.

@neganp, am I understanding you correctly?

With that union type, we can have more precision in our types, which helps be more idiomatic with elm with regards to typifying things for readability and maintenance. I think that is what you're saying and if so, I'm in agreement. I'm just confused on what prompted the comment since they seem to align completely. 

Let me know if I missed something here. I'm trying to clarify for understanding and hopefully not be difficult since sometimes it's hard to tell that from text.

**Comment by leojpod** [comment]
it was marked as something to maybe do 😄 . If I get it right, it's not optional it has to be there has it not?

**Comment by tuxagon** [comment]
@leojpod Yes. The maybe is actually tied to whether it should be in a stub, not whether the union type should exist. The union type is desired for tests regardless of whether it is prepopulated for the student in the stub. 

Ultimately, it should show up in the stub for compilation purposes, though.

**Comment by leojpod** [comment]
@tuxagon yep that was my point (compilation purposes), so that the tests can refer to the error type defined in the stub.

**Comment by mpizenberg** [comment]
Hi everyone, I'm preparing to do a little bit of cleaning and updating in the elm track, which should take roughly two weekends I hope. It seems that this has already been merged with strings as errors. I'll close this issue for now. Don't hesitate to open a specific one to improve the error type if you wish latter.
