### ISSUE TITLE
Include instructions for globally installing dependencies

### ISSUE THREAD

**Issue by neganp** [exercism/elm#182]
As written, the instructions for running the tests have NPM installing `elm` and `elm-test` in every exercise directory. This is fine, but could be avoided by installing them globally by running

    npm install -g elm elm-test

and setting up the executables once, instead of running 

    npm install

and waiting ~10 seconds in each exercise directory.

I'm by no means a Node expert, but is there a compelling reason to not do this?

**Comment by tuxagon** [comment]
`npm install` does become superfluous if you've installed globally, meaning you wouldn't have to run it again even if you changed directories. The only thing I can think of is if someone wants to keep things either 1) isolated or 2) they have a different version installed for something else and they don't want to overwrite it globally.

Are you referring to just changing the `README` in each project? I just want to be clear.

**Comment by neganp** [comment]
Clarity is good! 👍 

I'm talking about changing the [installation instructions](http://exercism.io/languages/elm/installation) and maybe the README template. I think installing the dependencies once is more palatable: having one copy of the deps feels tidier, and being able to run the code without the install step makes starting a new exercise a little bit quicker.

**Comment by tuxagon** [comment]
Ah, I see. I would say installing globally for the installation instructions is a good idea, then. Reason for which is that elm's installation instructions even say that. If it affects someone, the chances are good that they will know and take any necessary actions to accommodate their special circumstances.

https://www.npmjs.com/package/elm
https://www.npmjs.com/package/elm-test

**Comment by churchie317** [comment]
> I'm by no means a Node expert, but is there a compelling reason to not do this?

The only reason this might be discouraged in the Node community is because global dependencies are generally reserved for local tooling, and the community really encourages an application's dependencies to be listed in the `package.json`. Obviously, requiring something to be globally installed--i.e. absent from the dependency manifest--makes downloading an application's dependencies a little trickier than a simple `npm i` and can lead to scenarios where an application works in one environment but not others.

That said, I agree that changing the installation instructions and updating the README template is a good idea. We definitely want to encourage the community to write Elm in an idiomatic way and the community has unequivocally sided on `npm install -g elm-test`.

**Comment by tuxagon** [comment]
#198 closes this
