### ISSUE TITLE
Review Topics

### ISSUE THREAD

**Issue by tuxagon** [exercism/elm#201]
Right now, we are not leveraging topics in the `config.json` file, so it would be worthwhile to have a discussion about adding topics for each exercise.

Topics listed [here](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt)

**Comment by neganp** [comment]
I'm a little surprised that the topics aren't included in the problem-specification repo. In any case, it shouldn't be too hard to consult a different exercise track to get an initial topic list.

Do we have a use for the topics? Does that get displayed on the site somewhere?

**Comment by tuxagon** [comment]
@neganp This is detailed in the docs repo, which is what prompted me to look into this as a TODO

https://github.com/exercism/docs/blob/35cd26e62266b314c654d974aaa53170217a962f/language-tracks/configuration/exercises.md#topics

**Comment by churchie317** [comment]
Agreed. It is worth noting that the list above is non-exhaustive. We should absolutely make an effort to go through and label each exercise according to the list above but also be sure not to undo any designations just because they don't appear on that list.

At a glance the Python track seems to be a pretty good reference--naturally we should be careful to not copy/paste wholesale because Python is OOP, supports classes, etc.

**Comment by tuxagon** [comment]
I am going to close this since it was handled in #220. There are definitely improvements that can be made and I'd like to see those be explicitly specified vs just having this issue constantly be resurrected and ignored due to the ambiguous nature of this issue. Having topics now technically handles this in the current state.
