### ISSUE TITLE
Bob exercise - missed condition

### ISSUE THREAD

**Issue by AlejikDem** [exercism/elm#222]
Hello. In the "Bob exercise" in README file missed information about the condition "Calm down, I know what I'm doing!"

**Comment by tuxagon** [comment]
@AlejikDem thanks for noticing! That has been updated in the past 6 months and I didn't know about that. This could be a good first issue for someone, so I'll mark it as that in case someone wants to tackle it.

Some notes for anyone interested in contributing through this should know that the canonical version of the README text to describe this problem is found [here](https://github.com/exercism/problem-specifications/blob/master/exercises/bob/description.md). There is also a utility that can be used to automatically update the README to be correct, called `configlet`. In the elm repo, you can run `bin/fetch-configlet` from the root of the elm repo, which will fetch the latest release of configlet and place it in the `bin/` directory. After that, you can run `bin/configlet generate --only bob .`, which will regenerate the README for only the bob exercise.

It could be a good idea to run `bin/configlet generate .` instead; however, since there may be other READMEs that are out of sync.

**Comment by MrMovl** [comment]
Came here to fix just that so I gave it a go. Please take a look at the PRs comment, I am not sure what the proper protocol is here and if it is at all useful to merge just this one Readme.

Thanks @tuxagon for the nice explanation, creating my first PR was a pleasant experience because of you ;)
