### ISSUE TITLE
elm-test not recognizing project root directory

### ISSUE THREAD

**Issue by Deepakkoli93** [exercism/elm#232]
Trying to run elm-test for the hello-world exercise. It prints the following:
"It looks like you're running elm-test from within your tests directory. Please run elm-test from your project's root directory, where its elm-package.json lives!"

I'm running it from ~/Exercism/elm/hello-world directory

**Comment by tuxagon** [comment]
If you run the following on the terminal, what do you see?
```
$ elm --version
```
 If you see `0.19.0`, that might be your problem. You can refer to [this](https://github.com/exercism/elm/issues/229#issuecomment-419911952) on installing the previous version of elm.

I am working with others in the exercism team to figure out why you are not receiving the 0.19 updated exercise. The red flag being the presence of `elm-package.json`.

Let me know if this issue persists after installing 0.18. I will keep this open right now and not prematurely close it out.

**Comment by lwaite2010** [comment]
I've installed `0.18.0`, but seem to still be having an issue. I manually created an `elm-package.json` file in the project folder and copied over what was deleted in the commit, but I am still getting the same error.

**Comment by tuxagon** [comment]
@lwaite2010 are you using the `elm-test` that is compatible with 0.18? I think the version is `0.18.3`.

**Comment by lwaite2010** [comment]
It looks like I'm using `0.18.3-beta3`. I'll install just `0.18.3` and see if that works.

**Comment by lwaite2010** [comment]
Installing `elm-test@0.18.3` is giving me the same result.

**Comment by tuxagon** [comment]
@lwaite2010 which docs do you mean? I completely understand everything being confusing. You really have to search and know some stuff in order for you to not trip over yourself. I'm a little grumpy that I cannot search for `0.18` packages with https://package.elm-lang.org/ for example. To be fair, elm is trying to get to a point where they have upgrade stability, but it's just not there yet because the enhancements are there for a reason. The intention is that the overall workflow of using elm is more important than trying to keep everything compatible with the newer version.

Did that work for you? @Deepakkoli93 what about you?

**Comment by Deepakkoli93** [comment]
Yes it's working with `elm 0.19.0` and `elm-test 0.10.9-beta10`. Thanks @lwaite2010 and @tuxagon

**Comment by estiens** [comment]
Hi there, I installed elm exercise track today and it does not work with elm 0.19. I do seem to have the new version of the exercises (have elm.json), however trying to run `elm test` gives me

```
 !  ~/e/e/hello-world  elm-test                                                                                                             
It looks like you're running elm-test from within your tests directory.
```

**Comment by estiens** [comment]
ah, I see now that we have to `npm install elm-test@beta`

works when that change is made

(also could upgrade elm-explorations/test to 1.1.0)
