### ISSUE TITLE
Leftover exercises in track

### ISSUE THREAD

**Issue by edgerunner** [exercism/elm#264]
Trying to submit PR's #253 -> #261  and #262 -> #263, I got rejected by the CI due to a couple of leftover exercise definitions in the `config.json` file. Then I noticed that those two somehow show up in the track as well

![leftover exercises in Elm track](https://user-images.githubusercontent.com/15765/64004461-f6b09f00-cb16-11e9-8817-c55b286ee13c.png)

I think we must remove those two ASAP. Or do they represent something else that must be fixed in another way? @iHiD 

### CI complaint

```
0.29s$ bin/configlet lint .
-> An exercise with slug 'isogram-duplicate' is referenced in config.json, but no implementation was found.
-> An exercise with slug 'binary-search-dupicate' is referenced in config.json, but no implementation was found.
The command "bin/configlet lint ." exited with 1.
```

**Comment by iHiD** [comment]
Hello @edgerunner.

So as a first thing, exercises should never be removed from the `config.json`. That would cause chaos on the website site.

For background: The original issue was that duplicate exercises were created by changing the uuids in https://github.com/exercism/elm/commit/68282ce82466b86fa6bb82da9963b9c15369f8fa - this was fixed by https://github.com/exercism/elm/commit/68282ce82466b86fa6bb82da9963b9c15369f8fa and also fixed in the database.

So, by way of solution, I've just broken my cardinal rule and deleted them from the config.json. I've done this because no-one had downloaded them on the website and so I can manually go through and remove all trace of them in the database (which I've just done), ie, we got super-lucky :)

**Comment by edgerunner** [comment]
It seems those two exercises never actually existed. I didn't see any trace of some code that would be downloaded as they are.

Does this mean it's ok to remove those two as in #265 ?

**Comment by iHiD** [comment]
> It seems those two exercises never actually existed. I didn't see any trace of some code that would be downloaded as they are.

They were duplicated within the database by changing the uuids of them in the config.json, so people could have seen two copies of them in the website.
