### ISSUE TITLE
What was it like to learn Elm?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/elm#269]
We’ve recently [started a project](https://exercism.io/blog/redesigning-tracks-in-partnership-with-chicago-university-and-sloan-foundation) to find the best way to design our tracks, in order to optimize the learning experience of students.

As a first step, we’ll be [examining the ways in which languages are unique and the ways in which they are similar](https://github.com/exercism/exercism/issues/5059). For this, we’d really like to use the knowledge of **everyone** involved in the Exercism community (students, mentors, maintainers) to answer the following questions:

1. How was your experience learning Elm? What was helpful while learning Elm? What did you struggle with? How did you tackle problems?
1. In what ways did Elm differ from other languages you knew at the time? What was hard to learn? What did you have to unlearn? What syntax did you have to remap? What concepts carried over nicely?

Could you spare 5 minutes to help us by answering these questions? It would greatly help us improve the experience students have learning Elm :)

_Note: this issue is **not** meant as a discussion, just as a place for people to post their own, personal experiences._

_Want to keep your thoughts private but still help? Feel free to email me at erik@exercism.io_

Thank you!

**Comment by mpizenberg** [comment]
Hi @ErikSchierboom, personally my learning experience dates back to early 2016 so I don't remember very well. But I've been mentoring a lot of newcommers to the language at meetups. I'd say that most difficult problem for people familiar with OOP is the lack of statements and loops. Elm is purely functional and total (kind of) so there is no escape to map, folds or recursion when dealing with collections.

The second issue due to purity, is that network and random (except with seed) requires a runtime since they are side effects (you get values back through an update function). And so it is not easy to experiment with them in the repl for example. One needs an Html.program etc. This also means that side effects concepts are currently impossible to tackle with the exercism format if I'm correct.

From my experience though, the compiler is so helpful that syntax isn't an issue even if it seems a bit strange at first. Maybe some parenthesis issue at the beginning because people might think they are for function calls where there are just here for prioritization of evaluation.

Then the other main difficulty in elm is code organization when scaling web apps. But that is out of exercism scope I think.

**Comment by leojpod** [comment]
Hi @ErikSchierboom, I'd second @mpizenberg for most points. 

I've learned elm in the early 2017 and started working with it as a paid job almost right after (the benefits of freelancing in a field with few competitions :smile:). 

I had a strong theoretical background in CS and I always like functional so to some extend the use of maps and fold was just like getting back on a bike after a long break. 

I strongly relate to the runtime thing: there are a couple of very nice package in elm to help with this but it took me a while to discover them (RemoteData ♥️ ). 

Another point that might be worth noting and that could be addressed with exercism is the Encoding/Decoding of JSON data to elm objects: 

- it is not a trivial task since elm is one of the only language that would force you to do such things, it's very easy to get a misconception of it.
- one of the main interest of this thing IMO is that it allows to keep a nice separation between data representation within elm and outside of elm: I love union types in elm and if I think that the JSON I receive from a service isn't to my taste I'll decode it in such ways that will make it easy for me to work with in elm and it feels like this point is often missed when learning elm. 
- it would fall under the scope of exercism's exercises: a test suite that runs decoder/encoders and the student should implement the actual encoder decoder. 

Regarding code organization: I agree with @mpizenberg once again, it can be messy when scaling up (I remember being puzzled a bit when adding elm-mdl into my first app).

**Comment by ErikSchierboom** [comment]
We're closing this issue as it was part of our research for the v3 version of Exercism which has [just been released](https://exercism.org/blog/exercism-v3-has-launched).

Thanks everyone for chipping in! It has been greatly appreciated.
