### ISSUE TITLE
Addition of more exercises

### ISSUE THREAD

**Issue by SiriusStarr** [exercism/elm#289]
Is there any particular objections to adding more (side) exercises to the Elm track?  (I'm happy to do the PRs.)  I would particularly like to see "wordy" added, as there are currently no exercises aimed at `elm/parser`, which is a valuable skill for students to practice, but there are other exercises I feel could be valuable as well.

**Comment by mpizenberg** [comment]
Oh you mentioning `elm/parser` reminded me of some work I had been holding off two months ago before becoming maintainer. I wanted to remove most unnecessary dependencies especially regex. You can see all the `Remove regex ...` commits there: https://github.com/mpizenberg/elm/commits/dependencies.
In particular I remember that I couldn't figure out how to do `phone-number` with just standard string functions. So I went a bit overboard in doing my own custom made parser, just for this XD https://github.com/mpizenberg/elm/commit/e800df749e5885dfda8a8bf07e630128996ee182. This definitely is a bad idea even though I don't like the regex one. Maybe using `elm/parser` for that one could make sense? Anyway, back to your question.

> Is there any particular objections to adding more (side) exercises to the Elm track?

Exercises are welcome! But I may add that if you have some time these few weeks before Christmas, Cedd and I would be super happy to get help on the research experiment matter: https://gist.github.com/mpizenberg/b686ed5723328d43266ccaff4d6fac09

Let me know by email at matthieu.pizenberg@gmail.com. Otherwise, exercises are also welcomed :)

**Comment by SiriusStarr** [comment]
> Maybe using `elm/parser` for that one could make sense?

I think `phone-number` is a bad candidate for `elm/parser` since it doesn't require well-formedness of non-digits (e.g. `"  ( 5 03-----    86753    09"` should be considered a valid phone number), so using `Parser` is massive overkill for something can be solved so concisely with either pattern matching or basic string functions, haha.  I would certainly commend a student for going through the work if they went about it that way but suggest they refactor to a simpler solution.

> Exercises are welcome!

Awesome, I'll start slowly porting things over as I get bored, haha.  I will leave this issue open for a bit longer in case other people have comments.

@mpizenberg  I feel I'm lacking context for this research experiment you linked?

**Comment by mpizenberg** [comment]
> something can be solved so concisely with either pattern matching or basic string functions

Well I think I wasn't able to solve it with string functions. Maybe I didn't try enough.

>  I feel I'm lacking context for this research experiment you linked?

So basically here is the project: https://exercism.io/blog/announcing-exercism-research
They are looking for tracks to participate and @ceddlyburge is helping me with this (well he's mostly doing it, I barely have time for coordination, I have to finish my thesis manuscript before Christmas ...). The first deadline is next Friday, to build a test runner, able to automatically test students submissions. This is happening here: https://github.com/exercism/elm-test-runner. Next is the creation of the exercises for this experiments. The discussion about all this is happening in channel #experiment-1 of exercism slack and the link I gave you before is a summary of this discussion.

**Comment by SiriusStarr** [comment]
@mpizenberg Ahh, gotcha, I'll hop into the slack channel; let me know if I can be of assistance.

**Comment by SiriusStarr** [comment]
I'm going to close this issue since there have been no further comments.  I'll continue to port exercises on the strict schedule of whenever I get around to it.  XD
