### ISSUE TITLE
Nucleotide Count - Instructions doesn't fully correspond to the task 

### ISSUE THREAD

**Issue by 552020** [exercism/elm#483]
I solved the exercise by relying more on the type annotations of the `nucleotideCounts` function (`nucleotideCounts : String -> NucleotideCounts`) and on the tests than on the instructions themselves, which say "If the string contains characters that aren't A, C, G, or T then it is invalid and you should signal an error." I check also a couple of the community solutions but no one of the few I checked is also implemented to signal an error, cause also this would generate an error since the expected output is NucleotideCounts . Not sure if this is on purpose.

**Comment by mpizenberg** [comment]
It seems that problem specification changed in October 2020: https://github.com/exercism/problem-specifications/commit/53df31f552ce037df54306b0c9f4b9a545a22205
And the instructions for that exercise was automatically synced to the new spec in February 2021: https://github.com/exercism/elm/commits/main/exercises/practice/nucleotide-count/.docs/instructions.md

So since that change, the description suggest to return an error in case there are wrong letters, though we didn't update the elm implementation and test suite.

We should change the elm exercise to reflect the problem spec change. PR welcome :)

**Comment by 552020** [comment]
Thank you @mpizenberg. I would like to update the exercise and the tests to reflect the specifications but I guess my programming skills are not ripe enough yet. I can imagine that the other way around, i.e. to modify the specs to reflect the tests till the exercise and the tests will be adapted is also a possible solution and much easier to implement. :-)

**Comment by mpizenberg** [comment]
@552020 Actually this is a rather easy and good first contribution if you'd want to give it a try. What one would need to do is to update the files inside the directory `exercises/practice/nucleotide-count/`.

We'd want the new function signature to return a `Maybe`, meaning it will be `Nothing` in case of a wrong input, or `Just { ... }` for a correct one.

```elm
nucleotideCounts : String -> Maybe NucleotideCounts
```

The files that would need updating are the following

 - `src/NucleotideCount.elm` which contains the starter template
 - `tests/Test.elm` to reflect the current canonical data for tests at https://github.com/exercism/problem-specifications/blob/main/exercises/nucleotide-count/canonical-data.json
 - `.meta/src/NucleotideCount.example.elm` to contain an example solution
 - `.meta/config.json` to add yourself in the contributors

If you feel you're up to the task, give it a try. If not we'll let it as is since it's a good first issue for someone else who would want to contribute, or for yourself once you've gained more confidence in what you think are your current obstacles. I'm happy to help in any case.
