### ISSUE TITLE
Treasure Factory Exercise Not testing Error Case

### ISSUE THREAD

**Issue by pwadsworth** [exercism/elm#585]
Part 4 of `Treasure Factory` asks to implement the `makeTreasureChest` function, which will be the only way to create a `TreasureChest`. This is meant to enforce constraints so that `TreasureChest`s are always secure and unique, but the tests do not check for that. For example, the following code passes the test but it does not enforce any of the requirements:

```
makeTreasureChest : Chest pwd treasure Conditions -> TreasureChest treasure
makeTreasureChest (Chest pwd treasure cond) =
    case cond of
        SecureAndUnique ->
            TreasureChest pwd treasure

        _ ->
            TreasureChest "" treasure
```
Returning a `Maybe TreasureChest` would facilitate removing the case types that should not return a `TreasureChest`.

**Comment by ceddlyburge** [comment]
Hi Pete. I didn't write this exercise, and I haven't solved in myself yet, but my understanding is that this is kind of ok.

The idea is that the definition of `makeTreasureChest` requires the conditions to be `{ conditions | securePassword : (), uniqueTreasure : () }`, so that you can only pass secure and unique things in to the `makeTreasureChest` function. If you have a look at the exemplar solution you will probably see what I mean.

It isn't really possible to test for this, which is why your example code above works.

We probably can add a rule to the automated analyser to check for this though. @jiegillet : do you agree?

If so we can add an issue for that to the analyser repo.

**Comment by ceddlyburge** [comment]
Hi Pete, I've added an issue to the analyser repo that will fix this.

As you can see you the [Example solution](https://github.com/exercism/elm/blob/main/exercises/concept/treasure-factory/.meta/Exemplar.elm), the idea is that the type signature of `makeTreasureChest` specifies the constraints, rather than the implementation.

Cheers, Cedd

**Comment by jiegillet** [comment]
Closed via https://github.com/exercism/elm-analyzer/pull/63
